name: Scheduled CI/CD

on:
  push:
    branches:
      - develop
      - feature/upgrade
#on:
#    schedule:
#        -   cron: "0 1,18,23 * * *"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v1
            -   uses: actions/setup-node@v1 #this installs node and npm for us
                with:
                    node-version: '20.x'
            -   uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
                with:
                    path: |
                        ~/.npm
                        $GITHUB_WORKSPACE/node_modules
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-
            -   name: Build
                run: |
                    npm install
                    npm build
            -   name: Deploy
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: dist
